version: '3.4'.

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.4
    environment:
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
        reservations:
          cpus: "0.15"
          memory: 512M
      placement:
        constraints:
          - node.role != manager
    networks:
      - wazuh
    volumes:
      - /mnt/swarm/wazuh/certs/root-ca.pem:/usr/share/wazuh-indexer/config/certs/root-ca.pem
      - /mnt/swarm/wazuh/certs/wazuh-indexer-key.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
      - /mnt/swarm/wazuh/certs/wazuh-indexer.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
      - /mnt/swarm/wazuh/certs/admin.pem:/usr/share/wazuh-indexer/config/certs/admin.pem
      - /mnt/swarm/wazuh/certs/admin-key.pem:/usr/share/wazuh-indexer/config/certs/admin-key.pem
      - /mnt/swarm/wazuh/indexer/data:/var/lib/wazuh-indexer
      - /mnt/swarm/wazuh/indexer/config/wazuh.indexer.yml:/usr/share/wazuh-indexer/config/opensearch.yml
      - /mnt/swarm/wazuh/indexer/config/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.4
    ports:
      - target: 514
        published: 514
        mode: host
        protocol: udp
      - target: 1514
        published: 1514
        mode: host
      - target: 1515
        published: 1515
        mode: host
      - target: 55000
        published: 55000
        mode: host
    environment:
      INDEXER_URL: https://wazuh-indexer:9200
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: PASS
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: wazuh-wui
      API_PASSWORD: PASS
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    volumes:
      - /mnt/swarm/wazuh/manager/api:/var/ossec/api/configuration
      - /mnt/swarm/wazuh/manager/config:/var/ossec/etc
      - /mnt/swarm/wazuh/manager/logs:/var/ossec/logs
      - /mnt/swarm/wazuh/manager/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
      - /mnt/swarm/wazuh/certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - /mnt/swarm/wazuh/certs/wazuh-manager.pem:/etc/ssl/filebeat.pem
      - /mnt/swarm/wazuh/certs/wazuh-manager-key.pem:/etc/ssl/filebeat.key
      - /mnt/swarm/wazuh/manager/filebeat/etc:/etc/filebeat
      - /mnt/swarm/wazuh/manager/filebeat/var:/var/lib/filebeat
    networks:
      - wazuh

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.4
    environment:
      INDEXER_USERNAME: admin
      INDEXER_PASSWORD: PASS
      WAZUH_API_URL: https://wazuh-manager
      API_USERNAME: wazuh-wui
      API_PASSWORD: PASS
    deploy:
    
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.wazuh-http.rule=Host(`wazuh.foo.bar`)
        - traefik.http.routers.wazuh-http.entrypoints=http
        - traefik.http.routers.wazuh-http.middlewares=https-redirect,crowdsec
        - traefik.http.routers.wazuh.rule=Host(`wazuh.foo.bar`)
        - traefik.http.routers.wazuh.entrypoints=https
        - traefik.http.routers.wazuh.middlewares=internal_ip_whitelist,crowdsec
        - traefik.http.routers.wazuh.tls=true
        - traefik.http.routers.wazuh.tls.certresolver=le
        - traefik.http.services.wazuh.loadbalancer.server.port=5601
    volumes:
      - /mnt/swarm/wazuh/certs/wazuh-dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - /mnt/swarm/wazuh/certs/wazuh-dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - /mnt/swarm/wazuh/certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - /mnt/swarm/wazuh/dashboard/config/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - /mnt/swarm/wazuh/dashboard/config/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    networks:
      - wazuh
      - traefik-public

networks:
  wazuh:
  traefik-public:
    external: true