version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - data:/data/
    env_file: vault.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
    ports:
      - 8004:80
    environment:
      - DOMAIN=https://vaultwarden.example.com
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=true
      - LOG_LEVEL=info
      - EXTENDED_LOGGING=true
#      - TZ="Europe/Berlin"
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: addr="IP-of-NAS",nolock,soft,rw
      device: ":/mnt/nfsshare/vaultwarden/data"
networks:
  public:
    external: true