# Source: https://github.com/boschkundendienst/guacamole-docker-compose.git
# networks
# create a network 'guacnetwork_compose' in mode 'overlay' as this is for Docker Swarm
networks:
  guacnetwork:
    driver: overlay

# services
services:
  # guacd
  guacd:
    image: guacamole/guacd
    networks:
      - guacnetwork
    restart: always
    volumes:
    - drive:/drive:rw
    - record:/record:rw
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  # postgres
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
  #    POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_PASSWORD_FILE: /run/secrets/guac_postgres
      POSTGRES_USER: guacamole_user
    image: postgres:16.4-bookworm
    networks:
      - guacnetwork
    volumes:
  #  - ./init:/docker-entrypoint-initdb.d:z
  #  - ./data:/var/lib/postgresql/data:Z
    - postgres:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    secrets:
      - guac_postgres

  # guacamole
  guacamole:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
  #    POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_PASSWORD_FILE: /run/secrets/guac_postgres
      POSTGRES_USER: guacamole_user
      # TOTP_ENABLED: "true"
    image: guacamole/guacamole:1.5.5
    networks:
      - guacnetwork
    volumes:
      - record:/record:rw
    ports:
## enable next line if not using nginx
    - 8088:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
#    - 8080/tcp
#    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
    secrets:
      - guac_postgres

########### optional ##############
  # nginx
#  nginx:
#   container_name: nginx_guacamole_compose
#   restart: always
#   image: nginx:latest
#   volumes:
#   - ./nginx/templates:/etc/nginx/templates:ro
#   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
#   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
#   ports:
#   - 8443:443
#   networks:
#     - guacnetwork_compose
####################################################################################
volumes:
  drive:
    driver_opts:
      type: "nfs"
      o: addr="IP-of-NAS",nolock,soft,rw
      device: ":/mnt/Docker/swarm/guacamole/drive"
  record:
    driver_opts:
      type: "nfs"
      o: addr="IP-of-NAS",nolock,soft,rw
      device: ":/mnt/Docker/swarm/guacamole/record"
  postgres:
    driver_opts:
      type: "nfs"
      o: addr="IP-of-NAS",nolock,soft,rw
      device: ":/mnt/Docker/swarm/guacamole/postgres"
secrets:
  guac_postgres:
    external: true
