version: '3.9'

services:
  guacdb2:
  #  hostname: guacdb
    image: mariadb:10.11.7
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/guac_db_root_pass
      MARIADB_DATABASE: 'guacamole_db'
      MARIADB_USER: 'guacamole_user'
      MARIADB_PASSWORD_FILE: /run/secrets/guac_db_user_pass
    volumes:
      - guac-mariadb:/var/lib/mysql
    secrets:
      - guac_db_root_pass
      - guac_db_user_pass
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      guac1:
       aliases:
          - guacdb
secrets:
  guac_db_root_pass:
    external: true
  guac_db_user_pass:
    external: true
volumes:
  guac-mariadb:
    driver_opts:
      type: "nfs"
      o: "addr="IP-of-NAS",nolock,soft,rw"
      device: ":/volume1/swarm/guac-db2"
networks:
  guac1:
    driver: overlay
  public:
    external: true