version: '3.9'

services:

  ghost:
    image: ghost:5-alpine
#    restart: always
    ports:
      - 8088:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: MySuperSecretPassw0rd
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://blog.example.com
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content
#    secrets:
#      - ghost_mysql_pwd

  db:
    image: mariadb:10.11.7
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/ghost/ghost_mysql_pwd
    volumes:
      - db:/var/lib/mysql
    secrets:
      - ghost_mysql_pwd

volumes:
  ghost:
    driver_opts:
      type: "nfs"
      o: addr="IP-of-NAS",nolock,soft,rw
      device: ":/mnt/Docker/ghost/content"
  db:
    driver_opts:
      type: "nfs"
      o: "addr="IP-of-NAS",nolock,soft,rw"
      device: ":/mnt/Docker/ghost/mariadb"

secrets:
  ghost_mysql_pwd:
    external: true

